/*
*Author: Omar Hossain
*Start Date: November 6, 2025
*Last Modified: December 2024
*Purpose: Header file for the LoginDialog class.
*This class defines the structure and behavior of the login interface.
*It manages user authentication by verifying credentials through SystemController
*and passing the authenticated User object to the main application window.
*Dependencies: user.h, admin.h, systemController.h, QDialog, QMessageBox.
*/
#ifndef LOGINDIALOG_H
#define LOGINDIALOG_H

#include <QDialog>
#include <QMessageBox>
#include "user.h"
#include "admin.h"
#include "systemController.h"

// Forward declaration of the UI namespace generated by Qt Designer
namespace Ui {
class LoginDialog;
}

/*
* LoginDialog class
* -----------------
* Inherits from QDialog and provides functionality for user authentication.
* The class handles login validation through SystemController, user role identification,
* and communication with the main Dialog window after successful login.
*/
class LoginDialog : public QDialog
{
    Q_OBJECT  // Enables Qt's signal-slot mechanism

public:
    // Constructor and Destructor
    explicit LoginDialog(SystemController* controller, QWidget *parent = nullptr);
    ~LoginDialog();

    // Returns true if login was successful
    bool isAuthenticated() const;

    // Returns pointer to the authenticated user (admin or regular)
    User* getAuthenticatedUser() const;

private slots:
    // Slot functions triggered by UI button clicks
    void onLoginClicked();
    void onCancelClicked();

private:
    Ui::LoginDialog *ui;     // Pointer to the UI form generated by Qt Designer
    bool authenticated;      // Tracks if the user successfully logged in
    User* currentUser;       // Pointer to the currently logged-in user

    SystemController* systemController;  // Reference to system controller
};

#endif // LOGINDIALOG_H
